apiVersion: v1
kind: Secret
metadata:
  name: settlement-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  oracle-password: {{ .Values.oracle.password | quote }}
  oracle-app-user: {{ .Values.oracle.appUser | quote }}
  oracle-app-password: {{ .Values.oracle.appPassword | quote }}
  ConnectionStrings__Oracle: {{ .Values.oracle.connectionString | quote }}
  RabbitMq__Password: {{ .Values.rabbitMq.password | quote }}
