apiVersion: apps/v1
kind: Deployment
metadata:
  name: settlement-worker
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.worker.replicas }}
  selector:
    matchLabels:
      app: settlement-worker
  template:
    metadata:
      labels:
        app: settlement-worker
    spec:
      containers:
        - name: worker
          image: {{ .Values.worker.image | quote }}
          imagePullPolicy: {{ .Values.worker.pullPolicy }}
          envFrom:
            - configMapRef:
                name: settlement-config
            - secretRef:
                name: settlement-secrets
