version: "3.9"

services:
  app:
    build: .
    container_name: distributed-event-bus-app
    ports:
      - "3000:3000"
    environment:
      REDIS_URL: ${REDIS_URL}
    depends_on:
      - redis
    command: npm run start:redis
    volumes:
      - .:/app
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: redis-bus
    ports:
      - "6379:6379"
