# core/decision.py

from dataclasses import dataclass, asdict
from datetime import datetime
from typing import Dict, Optional, Any

from core.rules import RuleResult


@dataclass
class TradeDecision:
    """Represents a trade idea generated by aggregated confluence."""
    pair: str
    direction: str            # 'LONG', 'SHORT', or 'NONE'
    entry: float
    stop: float
    target: float
    score: float              # aggregated continuous score in [-1,1]
    rationale: str
    timestamp: str
    meta: Dict[str, Any] = None

    def as_dict(self) -> Dict:
        return asdict(self)


class DecisionEngine:
    """
    Aggregates rule outputs (discrete + continuous) into a final trade decision.
    This engine is conservative by default (mitigates short-term noise).
    """

    # sensible defaults; can be overridden by passing config to __init__
    DEFAULT_CONFIG = {
        "weights": {"structure": 0.3, "momentum": 0.3, "flow": 0.2, "volatility": 0.2},
        "weighted_score_threshold": 0.35,   # threshold on weighted continuous score
        "required_votes": 3,                # require 3/4 discrete signals for auto-pass
        "atr_multiplier": 1.5,              # stop = entry +/- atr_multiplier * ATR
        "risk_reward": 2.0,                 # target distance = risk_reward * stop_distance
        "fallback_stop_pct": 0.01,          # 1% fallback stop if no ATR
        "min_stop_pct": 0.003,              # minimum stop 0.3%
        "max_stop_pct": 0.08,               # maximum stop 8%
        "regime_protect": True,             # respect regime info in signals.meta['regime']
    }

    def __init__(self, pair: str, latest_price: float, config: Optional[Dict[str, Any]] = None):
        self.pair = pair
        self.latest_price = float(latest_price)
        cfg = dict(self.DEFAULT_CONFIG)
        if config:
            cfg.update(config)
            # if nested weights provided, merge them
            if "weights" in config:
                cfg["weights"] = {**self.DEFAULT_CONFIG["weights"], **config["weights"]}
        self.cfg = cfg

    def aggregate_score(self, signals: RuleResult) -> float:
        """
        Combine continuous scores using configured weights if available,
        otherwise fall back to averaging discrete signals.
        Returns a score in [-1.0, 1.0].
        """
        # Prefer continuous scores provided by RuleResult
        scores = {}
        if isinstance(signals, RuleResult) and getattr(signals, "scores", None):
            scores = signals.scores or {}
        # if no continuous scores, build from discrete values
        if not scores:
            sdict = signals.as_dict()
            # take only the discrete keys
            for k in ("structure", "momentum", "flow", "volatility"):
                scores[k] = float(sdict.get(k, 0))
        # apply weights
        weights = self.cfg["weights"]
        weighted_sum = 0.0
        weight_total = 0.0
        for k, w in weights.items():
            v = float(scores.get(k, 0.0))
            weighted_sum += w * v
            weight_total += w
        if weight_total == 0:
            return 0.0
        aggregated = weighted_sum / weight_total
        # clamp
        if aggregated > 1.0:
            aggregated = 1.0
        if aggregated < -1.0:
            aggregated = -1.0
        return round(aggregated, 4)

    def _discrete_vote(self, signals: RuleResult) -> Dict[str, int]:
        """
        Count discrete votes for bullish / bearish across the 4 rule outputs.
        Returns {"bull": int, "bear": int}
        """
        s = signals.as_dict()
        bull = 0
        bear = 0
        for k in ("structure", "momentum", "flow", "volatility"):
            v = int(s.get(k, 0))
            if v > 0:
                bull += 1
            elif v < 0:
                bear += 1
        return {"bull": bull, "bear": bear}

    def _extract_atr(self, signals: RuleResult) -> Optional[float]:
        """
        Pull ATR (mid or short) from signals.meta if present.
        Returns a positive float or None.
        """
        meta = getattr(signals, "meta", {}) or {}
        # the rules implementation stores volatility meta under 'volatility'
        vol_meta = meta.get("volatility") if isinstance(meta, dict) else None
        if isinstance(vol_meta, dict):
            # prefer mid_atr then short_atr
            atr = vol_meta.get("mid_atr") or vol_meta.get("short_atr")
            try:
                if atr and float(atr) > 0:
                    return float(atr)
            except Exception:
                pass
        # fallback: signals.meta might include top-level ATR names
        if meta.get("mid_atr"):
            try:
                if float(meta["mid_atr"]) > 0:
                    return float(meta["mid_atr"])
            except Exception:
                pass
        return None

    def derive_levels(self, direction: str, signals: RuleResult) -> Dict[str, float]:
        """
        Use ATR if available to build dynamic stop/target levels.
        Returns dict(entry, stop, target). Entry = latest_price by default.
        """
        entry = float(self.latest_price)
        rr = float(self.cfg.get("risk_reward", 2.0))
        atr = self._extract_atr(signals)
        stop = 0.0
        target = 0.0

        # compute stop distance
        if atr and atr > 0:
            stop_dist = float(self.cfg["atr_multiplier"]) * atr
            # ensure stop_pct within bounds
            stop_pct = stop_dist / (entry + 1e-12)
            stop_pct = max(self.cfg["min_stop_pct"], min(stop_pct, self.cfg["max_stop_pct"]))
            stop_dist = stop_pct * entry
        else:
            # fallback percent-based stop
            stop_pct = float(self.cfg["fallback_stop_pct"])
            stop_dist = stop_pct * entry

        if direction == "LONG":
            stop = round(entry - stop_dist, 8)
            target = round(entry + rr * stop_dist, 8)
        elif direction == "SHORT":
            stop = round(entry + stop_dist, 8)
            target = round(entry - rr * stop_dist, 8)
        else:
            stop = 0.0
            target = 0.0

        # ensure stop is positive and meaningful
        if stop <= 0:
            # fallback to tiny stop
            stop = round(entry * (1 - max(self.cfg["min_stop_pct"], 0.001)), 8) if direction == "LONG" else round(entry * (1 + max(self.cfg["min_stop_pct"], 0.001)), 8)

        return {"entry": entry, "stop": stop, "target": target, "atr_used": atr}

    def determine_direction(self, signals: RuleResult) -> str:
        """
        Conservative direction decision:
        - Pass immediately if discrete majority (>= required_votes) in one direction.
        - Otherwise use weighted continuous score and threshold.
        - Returns 'LONG', 'SHORT' or 'NONE'.
        """
        votes = self._discrete_vote(signals)
        req_votes = int(self.cfg.get("required_votes", 3))
        if votes["bull"] >= req_votes and votes["bull"] > votes["bear"]:
            return "LONG"
        if votes["bear"] >= req_votes and votes["bear"] > votes["bull"]:
            return "SHORT"

        # no clear majority -> use weighted score
        score = self.aggregate_score(signals)
        thr = float(self.cfg.get("weighted_score_threshold", 0.35))
        if score >= thr:
            return "LONG"
        if score <= -thr:
            return "SHORT"
        return "NONE"

    def build_decision(self, signals: RuleResult) -> Optional[TradeDecision]:
        """
        Compose final TradeDecision or None if no high-confidence signal.
        This applies regime protection and liquidity/regime-aware filtering.
        """
        # respect regime protection if present in signals.meta
        meta = getattr(signals, "meta", {}) or {}
        regime = meta.get("regime")  # expected: +1 bullish, -1 bearish, 0 neutral
        direction = self.determine_direction(signals)

        # regime protection: do not open trades that go against strong regime
        if self.cfg.get("regime_protect", True) and regime is not None and regime != 0:
            if regime > 0 and direction == "SHORT":
                return None
            if regime < 0 and direction == "LONG":
                return None

        if direction == "NONE":
            return None

        # final aggregated score (for transparency)
        agg_score = self.aggregate_score(signals)

        # derive levels with volatility-aware sizing
        levels = self.derive_levels(direction, signals)
        entry = levels["entry"]
        stop = levels["stop"]
        target = levels["target"]

        # rationale building
        votes = self._discrete_vote(signals)
        reasons = []
        reasons.append(f"votes(bull={votes['bull']},bear={votes['bear']})")
        reasons.append(f"agg_score={agg_score:.3f}")
        if levels.get("atr_used"):
            reasons.append(f"atr={levels['atr_used']:.6f}")
        # include brief module-level meta flags (if present)
        flow_meta = (signals.meta or {}).get("flow", {})
        if isinstance(flow_meta, dict) and flow_meta.get("wall_detected"):
            reasons.append("wall_detected")
        rationale = "; ".join(reasons)

        return TradeDecision(
            pair=self.pair,
            direction=direction,
            entry=round(entry, 8),
            stop=round(stop, 8),
            target=round(target, 8),
            score=round(agg_score, 4),
            rationale=rationale,
            timestamp=datetime.utcnow().isoformat(),
            meta={"decision_cfg": self.cfg, "signals_meta": signals.meta},
        )
