repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.8
    hooks:
      - id: ruff
        args: [--fix]
        files: ^practice/python/modern_setup/
      - id: ruff-format
        files: ^practice/python/modern_setup/

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        files: ^practice/python/modern_setup/
        additional_dependencies: []
