apiVersion: v1
kind: ConfigMap
metadata:
  name: settlement-config
  namespace: settlement
data:
  ASPNETCORE_ENVIRONMENT: Production
  DOTNET_ENVIRONMENT: Production
  OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317

---
apiVersion: v1
kind: Secret
metadata:
  name: settlement-secrets
  namespace: settlement
type: Opaque
stringData:
  oracle-password: settlement
  oracle-app-user: settlement
  oracle-app-password: settlement

