apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - rabbitmq.yaml
configMapGenerator:
  - name: settlement-config
    namespace: settlement
    behavior: replace
    envs:
      - settlement.env
secretGenerator:
  - name: settlement-secrets
    namespace: settlement
    envs:
      - secret.env
patches:
  - path: local-patch.yaml
