// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using Settlement.Infrastructure.Persistence;

#nullable disable

namespace Settlement.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SettlementDbContext))]
    partial class SettlementDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Settlement.Infrastructure.Persistence.Entities.AuditEventEntity", b =>
                {
                    b.Property<Guid>("AuditEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<string>("CausationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("NVARCHAR2(128)");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("NVARCHAR2(128)");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("NVARCHAR2(1024)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.Property<string>("TradeId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)");

                    b.Property<int>("TradeVersion")
                        .HasColumnType("NUMBER(10)");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("RAW(16)");

                    b.HasKey("AuditEventId");

                    b.HasIndex("WorkflowId");

                    b.HasIndex("TradeId", "TradeVersion", "OccurredAt");

                    b.ToTable("AUDIT_EVENTS", (string)null);
                });

            modelBuilder.Entity("Settlement.Infrastructure.Persistence.Entities.InvoiceEntity", b =>
                {
                    b.Property<Guid>("InvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<DateTimeOffset>("GeneratedAt")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("NVARCHAR2(128)");

                    b.Property<Guid>("SettlementId")
                        .HasColumnType("RAW(16)");

                    b.HasKey("InvoiceId");

                    b.HasIndex("InvoiceNumber")
                        .IsUnique();

                    b.HasIndex("SettlementId")
                        .IsUnique();

                    b.ToTable("INVOICES", (string)null);
                });

            modelBuilder.Entity("Settlement.Infrastructure.Persistence.Entities.OutboxMessageEntity", b =>
                {
                    b.Property<Guid>("OutboxMessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.Property<DateTimeOffset?>("DeadLetteredAt")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.Property<string>("LastError")
                        .HasMaxLength(1024)
                        .HasColumnType("NVARCHAR2(1024)");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("NVARCHAR2(128)");

                    b.Property<DateTimeOffset?>("NextAttemptAt")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("NCLOB");

                    b.Property<string>("PayloadHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("NVARCHAR2(128)");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("NVARCHAR2(32)");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("RAW(16)");

                    b.HasKey("OutboxMessageId");

                    b.HasIndex("MessageType", "PayloadHash")
                        .IsUnique();

                    b.HasIndex("Status", "NextAttemptAt");

                    b.ToTable("OUTBOX_MESSAGES", (string)null);
                });

            modelBuilder.Entity("Settlement.Infrastructure.Persistence.Entities.PaymentRequestEntity", b =>
                {
                    b.Property<Guid>("PaymentRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("NVARCHAR2(128)");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("RAW(16)");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.HasKey("PaymentRequestId");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("InvoiceId")
                        .IsUnique();

                    b.ToTable("PAYMENT_REQUESTS", (string)null);
                });

            modelBuilder.Entity("Settlement.Infrastructure.Persistence.Entities.SettlementEntity", b =>
                {
                    b.Property<Guid>("SettlementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<decimal>("Amount")
                        .HasPrecision(24, 8)
                        .HasColumnType("DECIMAL(24,8)");

                    b.Property<DateTimeOffset>("CalculatedAt")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("NVARCHAR2(3)");

                    b.Property<string>("TradeId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)");

                    b.Property<int>("TradeVersion")
                        .HasColumnType("NUMBER(10)");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("RAW(16)");

                    b.HasKey("SettlementId");

                    b.HasIndex("WorkflowId")
                        .IsUnique();

                    b.ToTable("SETTLEMENTS", (string)null);
                });

            modelBuilder.Entity("Settlement.Infrastructure.Persistence.Entities.TradeEntity", b =>
                {
                    b.Property<string>("TradeId")
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)");

                    b.Property<int>("TradeVersion")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Commodity")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("NVARCHAR2(32)");

                    b.Property<string>("Counterparty")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("NVARCHAR2(128)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("NVARCHAR2(3)");

                    b.Property<string>("PayloadHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("NVARCHAR2(128)");

                    b.Property<decimal>("Price")
                        .HasPrecision(24, 8)
                        .HasColumnType("DECIMAL(24,8)");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(24, 8)
                        .HasColumnType("DECIMAL(24,8)");

                    b.Property<DateTime>("SettlementDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime>("TradeDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("NVARCHAR2(16)");

                    b.HasKey("TradeId", "TradeVersion");

                    b.ToTable("TRADES", (string)null);
                });

            modelBuilder.Entity("Settlement.Infrastructure.Persistence.Entities.WorkflowEntity", b =>
                {
                    b.Property<Guid>("WorkflowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("NVARCHAR2(128)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("NVARCHAR2(32)");

                    b.Property<string>("TradeId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)");

                    b.Property<int>("TradeVersion")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.Property<int>("WorkflowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("WorkflowId");

                    b.HasIndex("TradeId", "TradeVersion")
                        .IsUnique();

                    b.ToTable("SETTLEMENT_WORKFLOWS", (string)null);
                });

            modelBuilder.Entity("Settlement.Infrastructure.Persistence.Entities.WorkflowTransitionEntity", b =>
                {
                    b.Property<long>("WorkflowTransitionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("WorkflowTransitionId"));

                    b.Property<string>("FromState")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("NVARCHAR2(32)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("NVARCHAR2(512)");

                    b.Property<int>("Sequence")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("ToState")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("NVARCHAR2(32)");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("RAW(16)");

                    b.HasKey("WorkflowTransitionId");

                    b.HasIndex("WorkflowId", "Sequence")
                        .IsUnique();

                    b.ToTable("WORKFLOW_TRANSITIONS", (string)null);
                });

            modelBuilder.Entity("Settlement.Infrastructure.Persistence.Entities.AuditEventEntity", b =>
                {
                    b.HasOne("Settlement.Infrastructure.Persistence.Entities.WorkflowEntity", "Workflow")
                        .WithMany("AuditEvents")
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("Settlement.Infrastructure.Persistence.Entities.InvoiceEntity", b =>
                {
                    b.HasOne("Settlement.Infrastructure.Persistence.Entities.SettlementEntity", "Settlement")
                        .WithOne("Invoice")
                        .HasForeignKey("Settlement.Infrastructure.Persistence.Entities.InvoiceEntity", "SettlementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Settlement");
                });

            modelBuilder.Entity("Settlement.Infrastructure.Persistence.Entities.PaymentRequestEntity", b =>
                {
                    b.HasOne("Settlement.Infrastructure.Persistence.Entities.InvoiceEntity", "Invoice")
                        .WithOne("PaymentRequest")
                        .HasForeignKey("Settlement.Infrastructure.Persistence.Entities.PaymentRequestEntity", "InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("Settlement.Infrastructure.Persistence.Entities.SettlementEntity", b =>
                {
                    b.HasOne("Settlement.Infrastructure.Persistence.Entities.WorkflowEntity", "Workflow")
                        .WithOne("Settlement")
                        .HasForeignKey("Settlement.Infrastructure.Persistence.Entities.SettlementEntity", "WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("Settlement.Infrastructure.Persistence.Entities.WorkflowEntity", b =>
                {
                    b.HasOne("Settlement.Infrastructure.Persistence.Entities.TradeEntity", "Trade")
                        .WithOne("Workflow")
                        .HasForeignKey("Settlement.Infrastructure.Persistence.Entities.WorkflowEntity", "TradeId", "TradeVersion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trade");
                });

            modelBuilder.Entity("Settlement.Infrastructure.Persistence.Entities.WorkflowTransitionEntity", b =>
                {
                    b.HasOne("Settlement.Infrastructure.Persistence.Entities.WorkflowEntity", "Workflow")
                        .WithMany("Transitions")
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("Settlement.Infrastructure.Persistence.Entities.InvoiceEntity", b =>
                {
                    b.Navigation("PaymentRequest");
                });

            modelBuilder.Entity("Settlement.Infrastructure.Persistence.Entities.SettlementEntity", b =>
                {
                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("Settlement.Infrastructure.Persistence.Entities.TradeEntity", b =>
                {
                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("Settlement.Infrastructure.Persistence.Entities.WorkflowEntity", b =>
                {
                    b.Navigation("AuditEvents");

                    b.Navigation("Settlement");

                    b.Navigation("Transitions");
                });
#pragma warning restore 612, 618
        }
    }
}
