### Health check
GET http://localhost:8888/health
Accept: application/json


### Register an asset (start order book)
POST http://localhost:8888/asset
Content-Type: application/json
Accept: application/json

{
  "asset_type": "crypto",
  "symbol": "SOLUSDT"
}


### View asset snapshot (stubbed)
GET http://localhost:8888/asset?asset_type=crypto&symbol=BTCUSDT&utc_offset=0
Accept: application/json


### List active assets (stubbed)
GET http://localhost:8888/asset/symbols?asset_type=crypto
Accept: application/json


### Deregister asset (stop order book)
DELETE http://localhost:8888/asset?asset_type=crypto&symbol=BTCUSDT
Accept: application/json
